### ISSUE TITLE
Mute System is not working and others

### ISSUE THREAD

**Issue by DeadlyGamer1** [XillaTech/Xilla-Discord-Core#2]
Firstly the tempmute will ban users 
here is the line that state that https://github.com/XillaTech/Xilla-Discord-Core/blob/master/Modules/UtilityBot/src/main/java/com/tobiassteely/utility/punishment/PunishmentCommands.java#L235-L236

It messages the users and then banned. As for the mute command, all it does is messages the users and nothing more. Users are able to still send a message. My suggestion is to have a mute role and apply it to them with a time for tempmute. Also, when you type the `history` command it just brings up an empty embed and `removewarn `does the same thing. Lasty Tempban will just perm. ban them.

**Comment by Alontrle** [comment]
I will look into this soon, the punishment system for Utility was never properly tested so that's why these issues are there. I will fix these then and post an update.

**Comment by Alontrle** [comment]
The utility module is deprecated and outdated. We are recoding the bot with a new module.
